"""empty message

Revision ID: 585121628953
Revises: 
Create Date: 2019-03-27 21:31:41.681137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '585121628953'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes_guardian', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes_guardian', 'tags')
    # ### end Alembic commands ###
