# Generated by Django 2.2 on 2019-04-09 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardian', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipeguardian',
            table='recipes_guardian',
        ),
    ]
